### PR TITLE
Use the same line-endings everywhere

### PR DESCRIPTION
**Pull request by bryant1410**
I converted everything to Unix LF line-endings (the typical ones used in code), to use the same line-endings everywhere in this repo, and avoid confusing line-ending diffs in commits, with:

```bash
find . -type f -print0 | xargs -0 dos2unix
```

(from https://stackoverflow.com/a/11929475/1165181)

### CODE REVIEW

**Comment by lbiester** [comment]
Fine for the CSVs, for the JS assets does it make sense, since those were written by others and copied over I don't think we would edit them anyways.

**Comment by bryant1410** [comment]
I reverted it. I don't think the original files contained Windows line-endings. And also I think it'd be better if we wouldn't keep our copies of 3rd party assets that are usually publicly served (and from CDNs, though GH Pages is also one).

**Comment by lbiester** [comment]
> I reverted it. I don't think the original files contained Windows line-endings. And also I think it'd be better if we wouldn't keep our copies of 3rd party assets that are usually publicly served (and from CDNs, though GH Pages is also one).

Are you suggesting switching to a CDN for these? I'd be fine with that and could make those changes later in the week.

**Comment by bryant1410** [comment]
> Are you suggesting switching to a CDN for these? I'd be fine with that and could make those changes later in the week.

They are already in a CDN because probably GitHub Pages uses one, but I'm still suggesting that we shouldn't keep copies of those, cause IMHO it doesn't make sense to have our own copies (the less code and boilerplate we have, the better).

**Comment by lbiester** [comment]
> > Are you suggesting switching to a CDN for these? I'd be fine with that and could make those changes later in the week.
> 
> They are already in a CDN because probably GitHub Pages uses one, but I'm still suggesting that we shouldn't keep copies of those, cause IMHO it doesn't make sense to have our own copies (the less code and boilerplate we have, the better).

Yeah, that's what I was saying (switch to an existing CDN)

**Pull request merged**
