### PR TITLE
Add LifeQA download

### PR DESCRIPTION
**Pull request by bryant1410**
There are many lines that changed because GitHub said there's a mix of Windows CRLF and Unix LF line endings, and they were changed automatically. But this change essentially makes LifeQA a "download", and adds some info.

### CODE REVIEW

**Comment by lbiester** [comment]
For the downloads page, I think you should fill in other download columns, like `downloadDescription`, `downloadLink`, and `downloadLinkNames`

**Comment by bryant1410** [comment]
I was thinking the same, but I saw it looked fine when I ran it locally. Note some links are already provided through the "data" and "software" fields (and others), and I think the paper title is self-describing. Also, as we created a web page for the paper, people can see more information there.

Do you think it renders well on the web page? Or something may be missing?

**Comment by lbiester** [comment]
I agree that it's somewhat self-explanatory, but still to be consistent with other entries, it would look better if you put the description and links (like in the second screenshot).
image
image

**Comment by bryant1410** [comment]
I added a description. About the links, I think the provided ones right now are enough.

**Pull request merged**
